### ISSUE TITLE
v0.4.0 doesn't work with Redmine 4.0.1 + Ruby 2.5.3 + Rails 4.2.11

### ISSUE THREAD

**Issue by 127-001** [haru/redmine_theme_changer#10]
Plugin v0.3.1 works well with Redmine 3.4.9
Plugin v0.4.0 doesn't work with  Redmine 4.0.1

Using Ruby 2.5.3 + Rails 4.2.11 in both cases (fresh install of redmine and plugin, no upgrade).
May be the plugin only works with Rails 5.x ?

**Error**:
```
ActionView::Template::Error (uninitialized constant ApplicationHelper::ThemeChangerUserSetting 
Did you mean?  ThemeChangerUserPreferencePatch):

plugins/redmine_theme_changer/lib/theme_changer_themes_patch.rb:24:in `get_theme'
plugins/redmine_theme_changer/lib/theme_changer_themes_patch.rb:32:in `current_theme'
app/helpers/application_helper.rb:1518:in `favicon_path'
app/helpers/application_helper.rb:1513:in `favicon'
app/views/layouts/base.html.erb:11:in `_app_views_layouts_base_html_erb__168936670_100515600'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by haru** [comment]
Redmine 4.0's Rails version is 5.2. Not 4.2.

See http://www.redmine.org/projects/redmine/wiki/RedmineInstall

**Comment by 127-001** [comment]
Hmm... yes, you're totally right. Something is seriously wrong in my bug report.
It should obviously not be the same rails version in both config. :-)

- I'm sure config A is Ruby 2.5.3 + Redmine 3.4.9 + Plugin v0.3.1 (working)
- I'm sure config B is Ruby 2.5.3 + Redmine 4.0.1 + Plugin v0.4.0 (not working)

Both are build with "bundle install", so Rails version should be 4.2 and 5.2
I will confirm this soon.

**Comment by 127-001** [comment]
Ok, so I confirm the obvious;  the non working config is
- Ruby 2.5.3 + **Rails 5.2.2** + Redmine 4.0.1 + Plugin v0.4.0

Error log is:
```
ActionView::Template::Error (uninitialized constant ApplicationHelper::ThemeChangerUserSetting
Did you mean?  ThemeChangerUserPreferencePatch):
     8: <meta name="description" content="<%= Redmine::Info.app_name %>" />
     9: <meta name="keywords" content="issue,bug,tracker" />
    10: <%= csrf_meta_tag %>
    11: <%= favicon %>
    12: <%= stylesheet_link_tag 'jquery/jquery-ui-1.11.0', 'application', 'responsive', :media => 'all' %>
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
  
plugins/redmine_theme_changer/lib/theme_changer_themes_patch.rb:24:in `get_theme'
plugins/redmine_theme_changer/lib/theme_changer_themes_patch.rb:32:in `current_theme'
app/helpers/application_helper.rb:1518:in `favicon_path'
app/helpers/application_helper.rb:1513:in `favicon'
app/views/layouts/base.html.erb:11:in `_app_views_layouts_base_html_erb__378599427_87849460'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
other info:
- The server runs windows 64bit (yeah, i know... but it's for historical reasons)
- Ruby 2.5.3 is also 64 bit (as well as the dev environment "msys2").
- Database is MySQL
- Database is the one from the working config (redmine 3.4.9) upgraded using "rake db:migrate"
- Without any plugin, the Redmine 4.0.1 config works ok.
- With common plugins (Lightbox2, clipboard) the Redmine 4.0.1 config works ok too.

May be it's related to the database upgrade, but the error doesn't seems related to the database.

**Comment by haru** [comment]
Something wrong.
Is plugins/redmine_theme_changer/app/models/theme_changer_user_setting.rb exists?

**Comment by 127-001** [comment]
> Is plugins/redmine_theme_changer/app/models/theme_changer_user_setting.rb exists?

Yes, it's the first thing I verified. Files were unziped from the "redmine_theme_changer-0.4.0.zip" in the release section.

I will try to rebuild the config on my personal PC. May be there is something wrong with the server configuration. And if it's still not working, I will have a personal config to debug/test :-)

**Comment by 127-001** [comment]
Ok. So I've rebuild the config on my personal PC with an empty database... and your plugin works !
So my problem is related to the server configuration or the database migration.

Anyway the issue is unrelated to your plugin, so you can close the issue. Sorry.
