### ISSUE TITLE
Don't work at issue page

### ISSUE THREAD

**Issue by ilbelyaev** [haru/redmine_theme_changer#17]
Hello! The new version does not work correctly. Applied theme not working on tab with tasks, tested on Redmine 4.2.1, 4.2.5.
Screenshots from Redmine 4.2.5 and New Release:
![изображение](https://user-images.githubusercontent.com/94981076/163355543-4f3238b0-db2c-4235-bdb5-e2cbcb03b86b.png)
![изображение](https://user-images.githubusercontent.com/94981076/163355724-9009c0b6-3fbe-4b90-ade1-11fc7ba533ee.png)
ScreenShots from Redmine 4.2.5 and Old Release:
![изображение](https://user-images.githubusercontent.com/94981076/163356030-61f0dda0-531a-480b-b9b1-1b2639f89ce3.png)
![изображение](https://user-images.githubusercontent.com/94981076/163356180-5f95add1-2f77-4c6e-abe8-017af6d21019.png)

**Comment by bmaehr** [comment]
@haru : Same here: Half of the pages use one theme other half the other. Really annoying.

**Comment by haru** [comment]
Thanks.
I've fixed.
