### ISSUE TITLE
The plug-in doesn't work with the latest redmine 6.0.1

### ISSUE THREAD

**Issue by muradurm** [haru/redmine_theme_changer#21]

**Comment by haru** [comment]
It works fine on my envrironment:Ruby 3.2 and Redmine 6.0.1.
Is there any error message?

**Comment by haru** [comment]
Sorry, I forgot to release new version of this plugin.
I've just release 0.7.0. Please try this one.

**Comment by muradurm** [comment]
> Sorry, I forgot to release new version of this plugin. I've just release 0.7.0. Please try this one.

Now it works.
Thanks.
