### ISSUE TITLE
ActionView::Template::Error (uninitialized constant ApplicationHelper::ThemeChangerUserSetting)

### ISSUE THREAD

**Issue by matheuslcruz** [haru/redmine_theme_changer#5]
Hi.

After installing v0.3.1 of this plugin and restart Redmine v3.4.5 I got this error:

ActionView::Template::Error (uninitialized constant ApplicationHelper::ThemeChangerUserSetting):
     8: <meta name="description" content="<%= Redmine::Info.app_name %>" />
     9: <meta name="keywords" content="issue,bug,tracker" />
    10: <%= csrf_meta_tag %>
    11: <%= favicon %>
    12: <%= stylesheet_link_tag 'jquery/jquery-ui-1.11.0', 'application', 'responsive', :media => 'all' %>
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
  plugins/redmine_theme_changer-0.3.1/lib/theme_changer_themes_patch.rb:24:in `get_theme'
  plugins/redmine_theme_changer-0.3.1/lib/theme_changer_themes_patch.rb:32:in `current_theme'
  app/helpers/application_helper.rb:1466:in `favicon_path'
  app/helpers/application_helper.rb:1461:in `favicon'
  app/views/layouts/base.html.erb:11:in `_app_views_layouts_base_html_erb__3245081575404114344_70234945482500'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by haru** [comment]
Please rename directory  `plugins/redmine_theme_changer-0.3.1` to `plugins/redmine_theme_changer`.

Redmine's plugin directory name must be exactly same with plugin name.

**Comment by matheuslcruz** [comment]
Hi. It worked. Thanx a lot.
