### ISSUE TITLE
Doesn't work with redmine 4.0.1.stable

### ISSUE THREAD

**Issue by mpauza** [haru/redmine_theme_changer#9]
I tried a lot of ways, but this plugin does not work with this version. 
Just shows error - contact your administrator.
Tried back to default theme and after it download, unzip and "rake".
After restart redmine shows error.
My version:
Environment:
  Redmine version                4.0.1.stable
  Ruby version                   2.6.0-p0 (2018-12-25) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production

**Comment by haru** [comment]
Is there any errors in a production.log?

**Comment by mpauza** [comment]
Looks like mysql table wasn't created:
ActionView::Template::Error (Mysql2::Error: Table 'redmine.theme_changer_user_settings' doesn't exist: SHOW FULL FIELDS FROM `theme_changer_user_settings`):
     8: <meta name="description" content="<%= Redmine::Info.app_name %>" />
     9: <meta name="keywords" content="issue,bug,tracker" />
    10: <%= csrf_meta_tag %>
    11: <%= favicon %>
    12: <%= stylesheet_link_tag 'jquery/jquery-ui-1.11.0', 'application', 'responsive', :media => 'all' %>
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>

I'm a bit new centOS+redmine, can you help me with it?
Create table manually?

**Comment by mpauza** [comment]
I found the issue.
Was something with gems and ruby.
after gem pristine -all
and
bundle exec rake RAILS_ENV=production redmine:plugins:migrate
Table was created.
Everything works.
Thank you
